name: "Publish packages"

on:
  push:
    tags: 
      - "v1.*-rc*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: | 
          npm install
          cd packages/widget
          npm install
          npm run front:build
          cp src/lib/package.json dist/
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}